FROM apache/spark:v3.2.2
MAINTAINER shawn <gentlestshawn@gmail.com>

COPY iceberg-spark-runtime-3.2_2.12-0.14.1.jar /opt/spark/jars/iceberg-spark-runtime-3.2_2.12-0.14.1.jar
COPY cache/spark-operators /opt/spark/jobs
